import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers/providers";
import { Navbar } from "@/components/component/navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chai & Study",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Providers>
          <main className="container">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
